### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by sdc9088** [IrineSistiana/udpme#2]
2022/03/16 11:33:08 listen udp 127.0.0.1:5353: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by nescirem** [comment]
> 2022/03/16 11:33:08 listen udp 127.0.0.1:5353: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

我这边也遇到了类似问题，Windows 10 19044.1586

**Comment by IrineSistiana** [comment]
Windows 10 19044.1586 没遇到这个问题。

看报错是因为权限。被反病毒软件或防火墙禁了，或者 5353 端口被占用了
